### ISSUE TITLE
Bluetooth not pairing with Ipad/Iphone

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [crystall1nedev/Inspiron-5570-KBR-Hackintosh#4]
EFI:
- Currently using the latest kext's for Intel Bluetooth Firmware, Itlwm/AirportItlwm (tried both, none work) and BlueToolFix,
- Not using Intel Bluetooth Injector

-  Upgraded from Big sur to Monterery, bluetooth was working fine on Big Sur.

Problem:
- After upgrading, Bluetooth does not work properly, tried updating all kexts, nothing worked 
- Sometimes Bluetooth discovers devices but is not able to pair with them, if i try from Iphone/Ipad an error dialog says 
 (Pairing/Connection Unsuccessfull, device not supported )
- If i initiate pairing connection from Hackintosh, pair request is sent and both devices confirm pairing code but then connection terminates and does not work further 
- Bluetooth preferences donot open ( crashes system preferences)

**Comment by crystall1nedev** [comment]
update the kexts from the official repositories, I haven't updated this repo in a while as my 5570 is not currently hackintoshed

**Comment by AbdurrehmanSubhani** [comment]
As stated earlier, all kexts are updated. I will look into any related issue on the kext sources, closing issue for now.
